# Generated by Django 5.1.1 on 2024-10-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodieRecipeSharing', '0002_recipepost_category_recipepost_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipepost',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='recipepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe/images/'),
        ),
    ]
