# Generated by Django 5.1.1 on 2024-12-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogIn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='post',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
