# Generated by Django 5.1.3 on 2024-11-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='category',
            field=models.CharField(choices=[('Comfort Food', 'Comfort Food'), ('International Eats', 'International Eats'), ('Breakfast & Brunch', 'Breakfast & Brunch'), ('Community Picks', 'Community Picks')], default='Uncategorized', max_length=50),
        ),
    ]
