# Generated by Django 5.1.3 on 2024-12-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0004_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepost',
            name='difficulty',
        ),
    ]
