# Generated by Django 5.1.1 on 2024-11-01 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JKB_RatingsandReviews', '0004_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
